import React, { useState } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { PlusIcon, SparklesIcon, PaperAirplaneIcon, TrashIcon } from '@heroicons/react/24/outline';
import { whatsappApi, aiApi } from '../services/api';
import toast from 'react-hot-toast';

const statusColors: Record<string, string> = {
  PENDING: 'badge-yellow',
  APPROVED: 'badge-green',
  REJECTED: 'badge-red',
  PAUSED: 'badge-gray',
};

const TemplatesPage: React.FC = () => {
  const [showModal, setShowModal] = useState(false);
  const [showAIModal, setShowAIModal] = useState(false);
  const [form, setForm] = useState({ name: '', category: 'UTILITY', language: 'en_US', body: '', footer: '', whatsappAccountId: '' });
  const [aiForm, setAiForm] = useState({ purpose: '', tone: 'professional', industry: '' });
  const qc = useQueryClient();

  const { data: templates } = useQuery({ queryKey: ['templates'], queryFn: () => whatsappApi.templates().then(r => r.data) });
  const { data: accounts } = useQuery({ queryKey: ['wa-accounts'], queryFn: () => whatsappApi.accounts().then(r => r.data) });

  const createMutation = useMutation({
    mutationFn: whatsappApi.createTemplate,
    onSuccess: () => { qc.invalidateQueries({ queryKey: ['templates'] }); setShowModal(false); toast.success('Template created'); },
  });

  const submitMutation = useMutation({
    mutationFn: whatsappApi.submitTemplate,
    onSuccess: () => { qc.invalidateQueries({ queryKey: ['templates'] }); toast.success('Template submitted for approval'); },
  });

  const handleAIGenerate = async () => {
    try {
      const { data } = await aiApi.generateTemplate(aiForm);
      setForm({ ...form, body: data.body, footer: data.footer || '', name: data.subject?.toLowerCase().replace(/\s+/g, '_') || '' });
      setShowAIModal(false);
      setShowModal(true);
      toast.success('Template generated by AI!');
    } catch {
      toast.error('AI generation failed');
    }
  };

  return (
    <div className="p-6">
      {showModal && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
          <div className="bg-white rounded-2xl w-full max-w-lg shadow-xl">
            <div className="px-6 py-4 border-b border-gray-200 flex items-center justify-between">
              <h2 className="text-lg font-semibold">New Template</h2>
              <button onClick={() => setShowModal(false)} className="text-gray-400">✕</button>
            </div>
            <div className="p-6 space-y-4">
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">Template Name *</label>
                  <input className="input-field" placeholder="template_name_en" value={form.name} onChange={e => setForm({ ...form, name: e.target.value.toLowerCase().replace(/\s+/g, '_') })} />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">Category</label>
                  <select className="input-field" value={form.category} onChange={e => setForm({ ...form, category: e.target.value })}>
                    {['MARKETING', 'UTILITY', 'AUTHENTICATION'].map(c => <option key={c} value={c}>{c}</option>)}
                  </select>
                </div>
              </div>
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">Language</label>
                  <select className="input-field" value={form.language} onChange={e => setForm({ ...form, language: e.target.value })}>
                    {['en_US', 'en_GB', 'es', 'fr', 'de', 'pt_BR', 'hi', 'ar', 'zh_CN'].map(l => <option key={l} value={l}>{l}</option>)}
                  </select>
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">WhatsApp Account</label>
                  <select className="input-field" value={form.whatsappAccountId} onChange={e => setForm({ ...form, whatsappAccountId: e.target.value })}>
                    <option value="">Select account...</option>
                    {(accounts || []).map((acc: any) => <option key={acc.id} value={acc.id}>{acc.name}</option>)}
                  </select>
                </div>
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Message Body *</label>
                <textarea className="input-field" rows={5}
                  placeholder="Hello {{1}}, your order {{2}} has been confirmed!"
                  value={form.body} onChange={e => setForm({ ...form, body: e.target.value })}
                />
                <p className="text-xs text-gray-500 mt-1">Use {'{{'}{'{1}'}{'}}'}  for variables</p>
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Footer (optional)</label>
                <input className="input-field" placeholder="Reply STOP to unsubscribe" value={form.footer} onChange={e => setForm({ ...form, footer: e.target.value })} />
              </div>
              <div className="flex gap-3 pt-2">
                <button onClick={() => setShowModal(false)} className="btn-secondary flex-1">Cancel</button>
                <button onClick={() => createMutation.mutate(form)} className="btn-primary flex-1">Create Template</button>
              </div>
            </div>
          </div>
        </div>
      )}

      {showAIModal && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
          <div className="bg-white rounded-2xl w-full max-w-md shadow-xl">
            <div className="px-6 py-4 border-b border-gray-200 flex items-center justify-between">
              <div className="flex items-center gap-2">
                <SparklesIcon className="w-5 h-5 text-indigo-500" />
                <h2 className="text-lg font-semibold">AI Template Generator</h2>
              </div>
              <button onClick={() => setShowAIModal(false)} className="text-gray-400">✕</button>
            </div>
            <div className="p-6 space-y-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Purpose *</label>
                <textarea className="input-field" rows={3} placeholder="Order confirmation, welcome message, appointment reminder..."
                  value={aiForm.purpose} onChange={e => setAiForm({ ...aiForm, purpose: e.target.value })} />
              </div>
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">Tone</label>
                  <select className="input-field" value={aiForm.tone} onChange={e => setAiForm({ ...aiForm, tone: e.target.value })}>
                    {['professional', 'friendly', 'formal', 'casual'].map(t => <option key={t} value={t}>{t}</option>)}
                  </select>
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">Industry</label>
                  <input className="input-field" placeholder="E-commerce, Healthcare..." value={aiForm.industry} onChange={e => setAiForm({ ...aiForm, industry: e.target.value })} />
                </div>
              </div>
              <div className="flex gap-3 pt-2">
                <button onClick={() => setShowAIModal(false)} className="btn-secondary flex-1">Cancel</button>
                <button onClick={handleAIGenerate} className="btn-primary flex-1">
                  <SparklesIcon className="w-4 h-4" />
                  Generate
                </button>
              </div>
            </div>
          </div>
        </div>
      )}

      <div className="flex items-center justify-between mb-6">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">Message Templates</h1>
          <p className="text-gray-500 text-sm mt-1">WhatsApp approved templates</p>
        </div>
        <div className="flex items-center gap-3">
          <button onClick={() => setShowAIModal(true)} className="btn-secondary">
            <SparklesIcon className="w-4 h-4 text-indigo-500" />
            AI Generate
          </button>
          <button onClick={() => setShowModal(true)} className="btn-primary">
            <PlusIcon className="w-4 h-4" />
            New Template
          </button>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
        {(templates || []).map((template: any) => (
          <div key={template.id} className="card p-5">
            <div className="flex items-start justify-between mb-3">
              <div>
                <h3 className="text-sm font-semibold text-gray-900">{template.name}</h3>
                <p className="text-xs text-gray-500 mt-0.5">{template.category} • {template.language}</p>
              </div>
              <span className={`badge ${statusColors[template.status]}`}>{template.status}</span>
            </div>
            <div className="bg-whatsapp-light rounded-xl p-3 mb-3">
              <p className="text-sm text-gray-800 leading-relaxed">{template.body}</p>
              {template.footer && <p className="text-xs text-gray-500 mt-1 border-t border-gray-200 pt-1">{template.footer}</p>}
            </div>
            <div className="flex gap-2">
              {template.status === 'PENDING' || template.status === 'APPROVED' ? null : (
                <button
                  onClick={() => submitMutation.mutate(template.id)}
                  className="flex items-center gap-1.5 px-3 py-1.5 text-xs bg-blue-50 text-blue-600 rounded-lg hover:bg-blue-100 flex-1 justify-center"
                >
                  <PaperAirplaneIcon className="w-3.5 h-3.5" />
                  Submit for Approval
                </button>
              )}
              <button className="p-1.5 text-gray-400 hover:text-red-600 hover:bg-red-50 rounded-lg ml-auto">
                <TrashIcon className="w-4 h-4" />
              </button>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};

export default TemplatesPage;
